
trigger:
- master

pool:
  vmImage: 'windows-2019'

steps:
- task: katalonTask@0
  inputs:
    version: '7.5.10'
    executeArgs: 'katalonc -noSplash -projectPath="C:\Users\902372\git\azure-devops-extension-samples\test.prj"-retry=0 -executionProfile="default" -browserType="Chrome"'