
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: katalonTask@0
  inputs:
    location: 'C:\Users\902372\Katalon_Studio_Windows_64-6.1.3'
    executeArgs: 'katalonc -noSplash -projectPath="C:\Users\902372\git\azure-devops-extension-samples\test.prj"  -retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="default" -browserType="Chrome"  -apiKey="0ae00a01-f0a9-44b5-bbec-708dbfcd1785" --config -proxy.auth.option=NO_PROXY -proxy.system.option=NO_PROXY  -proxy.system.applyToDesiredCapabilities=true'