
trigger:
- master

pool:
  vmImage: 'vs2017-win2016'

steps:
- task: katalonTask@0
  inputs:
    location: 'C:\Users\902372\Katalon_Studio_Windows_64-6.1.3'
    executeArgs: '-retry=0 -testSuitePath="Test Suites/TS_RegressionTest" -executionProfile="default" -browserType="Chrome"  -apiKey="b5fe0f55-2132-48bd-a634-846522141dfe"'
